# Generated by Django 3.2.8 on 2021-10-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='optionA',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='optionB',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='optionC',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='optionD',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quesionNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question',
            field=models.TextField(default='question'),
        ),
    ]
