# Generated by Django 3.2.8 on 2021-10-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_auto_20211028_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='correctAns',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='currentQues',
            field=models.IntegerField(default=1),
        ),
    ]
