# Generated by Django 3.2.8 on 2021-10-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_auto_20211030_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='currentQues',
        ),
    ]
